[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "aita-api"
version = "0.0.1"
description = "AITA API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["sqlmodel", "fastapi", "praw", "openai"]
